### ISSUE TITLE
Problem with name of test asset

### ISSUE THREAD

**Issue by Ser-Gen** [assetsjs/postcss-assets#35]
Windows can't create zip with files of your plugin because of this test file: https://github.com/borodean/postcss-assets/blob/develop/test/fixtures/alpha/Ich%20%E2%99%A5%20B%C3%BCcher.jpg

Symbols causing the problem: ♥, ü.
Could you rename that test file?

**Comment by borodean** [comment]
@Ser-Gen Those symbols there are to test character escaping by the library. Hmm, I need to think on how to test that in some other fashion.

**Comment by borodean** [comment]
@Ser-Gen [fixed in 4.0.0](https://github.com/assetsjs/postcss-assets/releases/tag/4.0.0).
