### ISSUE TITLE
loadPaths should be able to handle glob

### ISSUE THREAD

**Issue by tsm91** [assetsjs/postcss-assets#40]
Hi @borodean, I think the `loadPaths` option does not handle glob patterns. It would be an useful feature i think.

```js
assets({
  basePath: config.SRC_DIR,
  loadPaths: [path.join(config.DEST_DIR, '**/*')],
  relativeTo: 'public/css'
})
```

```bash
[21:54:48] Starting 'css'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: postcss-assets: /Users/tsm/Sites/__projects/gulp-starter/src/css/main.css:2:3: Asset not found or unreadable: sample.jpeg
Load paths:
  /Users/tsm/Sites/__projects/gulp-starter/src
  /Users/tsm/Sites/__projects/gulp-starter/public/**/*
.sample-bg-image {
  background-image: resolve("sample.jpeg"); }
```

**Comment by borodean** [comment]
@tsm91 whats the use case of this?

**Comment by tsm91** [comment]
@borodean if you have an asset-pipeline which is project-structure agnostic like [this](https://github.com/tsm91/gulp-starter).

In my case it doesn't cause any problems because the `images` gulp task will copy the image from anywhere to `public/images` but only because i use [gulp-flatten](https://github.com/armed/gulp-flatten) and because of the file watcher.

But i am sure there will be scenarios for other people when they would like to do something like `src/**/*` or `dist/**/*`.

**Comment by danielgamble** [comment]
I've just hit this myself as well, since we break things out into small modules we don't have a single root of assets anymore.

Being able to use: `name/apps/*/img/` would be sweet :)

**Comment by borodean** [comment]
@tsm91 @dan-gamble here you go: [introduced in 4.0.0](https://github.com/assetsjs/postcss-assets/releases/tag/4.0.0).

**Comment by dan-gamble** [comment]
Awesome <3

**Comment by tsm91** [comment]
cool, thanks

**Comment by borodean** [comment]
@tsm91 @dan-gamble btw, the plugin now accepts a single string as a `loadPaths` options, so instead of this:

```js
loadPaths: ['assets/**/img']
```

You can also write this:
```js
loadPaths: 'assets/**/img'
```

**Comment by dan-gamble** [comment]
Thanks for the heads up :)

**Comment by anotherWill** [comment]
Hi @borodean, how to write the options about this url.
`appName/src/assets/images/test.png`
and css in `appName/src/assets/css/main.css`
`resolve('test.png')`
I try it a long time and throw error. Assets not found or unreadable

**Comment by borodean** [comment]
@anotherWill well, I assume something like this should work:

```js
loadPaths: 'appName/src/assets/images'
```
