### ISSUE TITLE
Option for auto inline based on filesize

### ISSUE THREAD

**Issue by tsm91** [assetsjs/postcss-assets#41]
Hi @borodean, another useful feature would be to auto inline assets based on file size if specified.

Like [url-loader](https://github.com/webpack/url-loader)'s limit option.

**Comment by borodean** [comment]
@tsm91 there was such a feature in 1.x, however we decided to remove it – https://github.com/assetsjs/postcss-assets/issues/1

**Comment by borodean** [comment]
In the 1.x README you can see how it worked: https://github.com/assetsjs/postcss-assets/blob/aa5f4a45612b89ce57139e5477467428fa2eb2e0/README.md

Assets were converting every `url(...)` into either resolved or inlined url depending on the file size.

**Comment by borodean** [comment]
Oh, my bad. It wasn't 1.x, it was 0.x: https://github.com/assetsjs/postcss-assets/blob/941045f12958bbc7213ff326f5b09e267ad7383c/README.md

**Comment by tsm91** [comment]
The issue tells everything. If there would be an overwrite argument to resolve it would do the trick.

like `resolve('sample.jpeg', 2, false)` <-- false would mean, even if the file size meets the requirements, do not inline this

**Comment by borodean** [comment]
Leaving this unresolved by now.
