### ISSUE TITLE
Wrong path in multi-level dir

### ISSUE THREAD

**Issue by re54k** [assetsjs/postcss-assets#42]
Hi,
I got a same path with using `resolve` in different level directories.  e.g.
```
app/
  img/
    a.png
  css/
    x.css
    folder/
      y.css
```
Use the same code in `x.css` and `y.css`:
```
.someClass {
    background: resolve('a.png');
}
```

will be transform to
```
.someClass {
    background: url('../img/a.png');
}
```

But, `y.css` should be `../../img/a.png`.

Can you change the setting of relative mode, because not all css entry files are in the first level directory.

**Comment by borodean** [comment]
@Ser-Gen [fixed in 4.0.0](https://github.com/assetsjs/postcss-assets/releases/tag/4.0.0) by removing the `relativeTo` option and introducing the `retative` one: set it to `true` and you'll have you paths relative to the input file.

**Comment by borodean** [comment]
@re54k could you please share the config you use to process your stylesheets? How do you get multiple output points?

**Comment by re54k** [comment]
I use it in webpack with css-modules,  so,  not all css entry files are in the same level directory.
Thanks to the v4.0.0, option `relative: true` works well.

Some configs below,if helps.

webpack

``` js
...
loaders: [
    {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract('style', 'css?modules&importLoaders=1&localIdentName=[local]___[hash:base64:2]!postcss!sass'),
        include: path.join(__dirname, 'src/css')
    }
    ...
]
```


postcss

``` js
...
require('postcss-assets')({
    loadPaths: ['./src/img/'],
    relative: true
}),
...
```
