### ISSUE TITLE
How about > background-image: inline('mysvgfile.svg', 'fill-color-value');

### ISSUE THREAD

**Issue by perceptbe** [assetsjs/postcss-assets#44]
Thank you for this postcss plugin! 
A flexible inline image function was the one thing I truly missed when switching from Ruby SASS with Compass.

Anyway, I was thinking, this function could be really amazing if we would be able to pass a fill-color along so the function find/replaces the fill color in the svg before actually inlining it.
This way we can actually re-use the same svg-file, even if it needs to be in different colors.

You could even allow multiple value's to make multi-colored svg's 

value 1 replaces the first occurrence of fill=""
value 2 replaces the second occurrence of fill="" 
... 

Same could go for stroke values also :)

**Comment by borodean** [comment]
Leaving this unresolved by now. For now you can use this: https://github.com/TrySound/postcss-inline-svg.

**Comment by perceptbe** [comment]
Ok, thanks for the link to inline-svg.
