### ISSUE TITLE
inline does not work with version 4.x

### ISSUE THREAD

**Issue by DylanPiercey** [assetsjs/postcss-assets#49]
Using the simple config:

```js
postcssAssets({ cachebuster: true, basePath: "bin" })
```

Fails to find files in 4.x while 3.x works fine.

**Comment by borodean** [comment]
@DylanPiercey please provide an example of your setup with sample assets included, so the issue could be studied in detail.

**Comment by borodean** [comment]
@DylanPiercey closed because of no replies. Feel free to provide updates on this one to make it reopened.
