### ISSUE TITLE
`background-image` support?

### ISSUE THREAD

**Issue by FezVrasta** [assetsjs/postcss-assets#57]
Should it work if I use `background-image: inline(my.png)`?

It doesn't converts `inline` in this case...

**Comment by FezVrasta** [comment]
Ok actually it doesn't seem to work at all...

I enable it with:

```
require('postcss-assets')({
  loadPaths: ['src/images/']
})
```

My CSS are at `src/css/` and my images at `src/images`.

I try any of the postcss-assets features like:

```
background: resolve("icons/user.png")
```

(the icon is in `src/images/icons/user.png`)

But once compiled, I still see

```
background: resolve("icons/user.png")
```

Autoprefixer works so I doubt is a problem of my webpack build script...

**Comment by borodean** [comment]
@FezVrasta does the plugin logs anything into the terminal?

**Comment by FezVrasta** [comment]
sorry it was a problem with my build :/

**Comment by wesleyboar** [comment]
@FezVrasta, what was the problem with your build? Maybe others have the same problem and do not know. I am also unable to make this plugin have an effect as you described.

**Comment by FezVrasta** [comment]
Nothing, there was some additional compiler that was replacing mine.
